name: Build and Commit

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet && echo "No changes to commit" || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/index.js
          git commit -m "Update dist from action"
          git push
        if: env.changes == 'true'
